apiVersion: v1
kind: ConfigMap
metadata:
  name: pcsx2-wrapper
  namespace: gaming
data:
  pcsx2-qt: |
    #!/bin/sh
    exec nsenter --mount=/proc/1/ns/mnt --uts=/proc/1/ns/uts -- /opt/pcsx2/pcsx2-host-run.sh "$@"
