---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: rclone-config
  namespace: gaming
spec:
  encryptedData:
    rclone.conf: AgB2MRDT+1Ur5kNVRSoPvssd6VKMzAV6CTvJ/Cib9F+QZxQxQKB/jeKG4HH1MiwxPzcTe/W4sKjU5hOalQ7n3u/XlKlJCZzkXH62FjH+0NAZZ9o9ThFn634dymxHQ7x8FTDKWZXyqmvNyirM3iiY8VOP4KmrGeboTJ6qE+Xmz1CaavWrCG/G1UxKe4d0jOMOji1B3XfcYLJRMc4PrFB/uDEMtjuYaSHhUHm47sOEK4edT98C7csNQJNz/a6P8jcDgCmK6WuBUzgxfLj0pfMV63T0+EFieISqN9vOVylUCm0r9QYkY/h3cRYMSD0UQ4v/rwOLrqmo1rhnX7C5Yn91nZl8IK5ySRiatjjw8E8yDWH3YnUzer10kMJpjHh2969HejxyWdn+ya2dyfxrlBFoaQXyCU3h6gd6ljD9ucNHUL3tvt2vvmZZGKCXQcn0GYaxlHoUTYwCj5+xmrRJwxcnCwgFY9EyDdgssiVz9qoCRpTsdRToZeqXXzj0vceg4IqWAqCMViQbHZm+3mUrtRbnfwLEYWrLubmDasDbGuzgoboe3mQHC399IApgisymTrltNKskIK1F8AhL7oe4yHc04acoyyEiESNOHIKA/7Iw4iNn09iEYkitAYo3gbXof9I+o6YHTDBsAqwy0EEGTEIYev6rLgH55ExJbAa1Op7JKIZcv5gaJ9uj29Z1oYyxnSKomF8AIHtRa1xXC0errqwl70YlTd9XQdooYYdEpTQXzYUr5gvOKk5Sr0x3t40JA2ck6k4wnuEaYMgqf3t1X6QmJixTxpYzRnoBo4vLY8XpaN8g8NPJkHj6iTgrizQc1yLtWiLVVcOQPpDa6g/nexz1IVd8xd1vTMPoUaCbEM0uYuwjOMUJFbaawaLTegGJcUdZVr3D4fw1laByq9hPatYEwnpRQnts3FLLG2tsmU0fxWRzTM0TbUWn+r0KvSjuzfdqXbCL38adwq9D0Z5nhyxeVZA1oQA+J1QeO8TPHadvpU8kakH5UfNRPoUhK1lG8S9gmTHPet8ECHelrxkgsoK/8bqVATcEkcWjGC+93GoQGbo9/ALt1DV+aNJRqJAG5QCQinCoMLPfa7n5TeOfXwLs2ha4KRqKSen4Bt7E8lVSgkaXmrQg7wCnT8Tx4i/eUzMIgpioIryyxVIR7Z9ythlj7Az3qF5bWnJ/wUb/56A1mBIpl5qTK5H39Pczam6qETngoZaGttXYbHe/7j8cn+OiHHwiy6ncPJ6qnKL/DnGMUxmVaytOSvUCOPG5rjb3skWzPm1+MsfGolBv42LYClNHuAafUT1smJl/egBiKmP5Y9uijTlt7TZqTPRG6O5O6+PW5P5dYO/2gR2+lbYw52HIdHP9fheuzBpIgbKP7Iel+lOolwBvEYRPyNnzp+QNij6t36z6FDxPXpsdWRhWxbyopruO02qlRJWH
  template:
    metadata:
      name: rclone-config
      namespace: gaming
